main/urls.py
from django.urls import path

from django.conf import settings
from django.conf.urls.static import static

from . import views
urlpatterns=[
    path('',views.home,name='home'),
    path('all-news',views.all_news,name='all-news'),
    path('detail/<int:id>',views.detail,name='detail'),
    path('all-category',views.all_category,name='all-category'),
    path('category/<int:id>',views.category,name='category'),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

news/urls.py
from django.contrib import admin
from django.urls import path,include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('',include('main.urls')),
]

main/models.py
from django.db import models

class Category(models.Model):
    title=models.CharField(max_length=200)
    category_image=models.ImageField(upload_to='imgs/')

    class Meta:
        verbose_name_plural='Categories'

    def __str__(self):
        return self.title

# News Model
class News(models.Model):
    category=models.ForeignKey(Category,on_delete=models.CASCADE)
    title=models.CharField(max_length=300)
    image=models.ImageField(upload_to='imgs/')
    detail=models.TextField()
    add_time=models.DateTimeField(auto_now_add=True)

    class Meta:
        verbose_name_plural='News'

    def __str__(self):
        return self.title

# Comments
class Comment(models.Model):
    news=models.ForeignKey(News,on_delete=models.CASCADE)
    name=models.CharField(max_length=100)
    email=models.CharField(max_length=200)
    comment=models.TextField()
    status=models.BooleanField(default=False)

    def __str__(self):
        return self.comment

main/views.py
from django.shortcuts import render,redirect
from django.contrib import messages
from .models import News, Category,Comment
def home(request):
    first_news=News.objects.first()
    three_news=News.objects.all()[1:3]
    three_categories=Category.objects.all()[0:3]
    return render(request,'home.html',{
        'first_news':first_news,
        'three_news':three_news,
        'three_categories':three_categories
    })

# All News
def all_news(request):
    all_news=News.objects.all()
    return render(request,'all-news.html',{
        'all_news':all_news
    })

# Detail Page
def detail(request,id):
    news=News.objects.get(pk=id)
    if request.method=='POST':
        name=request.POST['name']
        email=request.POST['email']
        comment=request.POST['message']
        Comment.objects.create(
            news=news,
            name=name,
            email=email,
            comment=comment
        )
        messages.success(request,'Comment submitted but in moderation mode.')
    category=Category.objects.get(id=news.category.id)
    rel_news=News.objects.filter(category=category).exclude(id=id)
    comments=Comment.objects.filter(news=news,status=True).order_by('-id')
    return render(request,'detail.html',{
        'news':news,
        'related_news':rel_news,
        'comments':comments
    })

# Fetch all category
def all_category(request):
    cats=Category.objects.all()
    return render(request,'category.html',{
        'cats':cats
    })


# Fetch all category
def category(request,id):
    category=Category.objects.get(id=id)
    news=News.objects.filter(category=category)
    return render(request,'category-news.html',{
        'all_news':news,
        'category':category
    })

main/templates/all-news.html
{% extends 'base.html' %}
{% block content %}
<main class="container mt-3 mb-5">
	<h3 class="border-bottom pb-1 my-4">Bütün Haberler</h3>
    <!-- News Box -->
    {% for news in all_news %}
	<div class="card mb-4 shadow">
	  <div class="row no-gutters">
	    <div class="col-md-3">
            <img src="/media/{{news.image}}" class="card-img-top" alt="{{news.title}}">
	    </div>
	    <div class="col-md-8">
	      <div class="card-body">
	        <h5 class="card-title">{{news.title}}</h5>
	        <p style="color: black;" class="card-text">{{news.detail}}</p>
	        <p style="color: black;" class="card-text"><a href="/detail/{{news.id}}" class="btn btn-sm btn-primary">Hepsini Oku</a></p>
	      </div>
	    </div>
	  </div>
    </div>
    {% endfor %}
</main>
{% endblock %}

main/templates/base.html
{% load static %}
<!DOCTYPE html>
<html>

<head>
	<title>{% block title %}Home Page{% endblock %}</title>
	<link rel="stylesheet" type="text/css" href="{% static 'vendor/bs4/bootstrap.min.css' %}" />
	<script type="text/javascript" src="{% static 'vendor/jquery.min.js' %}"></script>
	<script type="text/javascript" src="{% static '/vendor/bs4/bootstrap.min.js' %}"></script>
	<link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0-alpha1/dist/css/bootstrap.min.css" rel="stylesheet"
		integrity="sha384-GLhlTQ8iRABdZLl6O3oVMWSktQOp6b7In1Zl3/Jr59b6EGGoI1aFkw7cmDA6j6gD" crossorigin="anonymous">

</head>

<body>

	<header>
		<nav class="navbar navbar-expand-lg navbar-dark bg-dark">
			<div class="container-fluid"> <a class="navbar-brand fw-bold" href="#"> <span class="border"> WEB</span> <span class="noborder">EWER</span></a> <button
					class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarNav" 
					aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation"> <span
						class="navbar-toggler-icon"></span> </button>
				<div style="padding-right: 150px;" class="collapse navbar-collapse" id="navbarNav">
					<ul class="navbar-nav d-flex justify-content-center w-100">
						<li class="nav-item"> <a class="nav-link" href="/">Anasayfa</a> </li>
						<li class="nav-item"> <a class="nav-link" href="{% url 'all-news' %}">Gündem</a> </li>
						<li class="nav-item"> <a class="nav-link" href="{% url 'all-category' %}">Kategoriler</a> </li>
					</ul>
				</div>
			</div>
		</nav>
	</header>
	<style>
		url("https://fonts.googleapis.com/css2?family=Heebo:wght@300;800&display=swap");

		* {
			margin: 0;
			padding: 0;
			box-sizing: border-box;
			font-family: "Heebo", sans-serif;
		}
		.border {
			background-color: #1da1f2;
			border-radius: 10%;
			padding: 0 5px;
		}
		.noborder {
			color: white;
		
		}

		body {
			overflow-x: hidden;
		}

		div.banner {
			width: 100%;
			min-height: 100vh;
			background-image: url(https://cdn.wallpapersafari.com/33/7/ZmRcgk.jpg);
			background-position: center;
			background-attachment: fixed;
			background-size: cover;
			background-repeat: no-repeat;
			display: flex;
			flex-direction: column;
			justify-content: center;
			align-items: center;
		}

		div.banner>h1 {
			font-size: 4.6em;
			font-weight: 800;
			color: #fff;
			text-shadow: 4px 4px 30px rgba(0, 0, 0, 0.8);
		}

		div.banner>h2 {
			color: #fff;
			font-size: 1.8em;
			letter-spacing: 2px;
		}

		div.content-area {
			width: 100%;
			min-height: 100vh;
		}
	</style>
	<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0-alpha1/dist/js/bootstrap.bundle.min.js"
		integrity="sha384-w76AqPfDkMBDXo30jS1Sgez6pr3x5MlQ1ZAGC+nuZB+EYdgRZgiwxhTBTkF7CXvN"
		crossorigin="anonymous"></script>


	{% block content %}
	{% endblock %}

	<hr />
	<footer>
		<div class="social">
		  <p>Bize Ulaşın</p>
		  <ul class="wrapper">
			<a href="https://www.linkedin.com/company/trair/" target="_blank">
			  <li class="icon linkedin">
				<span class="tooltip">LinkedIn</span>
				<span><i class="fab fa-linkedin"></i></span>
			  </li>
			</a>
			<a href="#" target="_blank">
			  <li class="icon facebook">
				<span class="tooltip">Facebook</span>
				<span><i class="fab fa-facebook-f"></i></span>
			  </li>
			</a>
			<a href="https://www.instagram.com/webewer_tr/" target="_blank">
			  <li class="icon instagram">
				<span class="tooltip">Instagram</span>
				<span><i class="fab fa-instagram"></i></span>
			  </li>
			</a>
			<a href="#" target="_blank">
			  <li class="icon twitter">
				<span class="tooltip">Twitter</span>
				<span><i class="fab fa-twitter"></i></span>
			  </li>
			</a>
		
		  </ul>
		</div>
		<div class="final_text"></div>
		<p class="text-center"> © TrAir Teknoloji Yatırımları A.Ş <br> Baştürk Holding İştirakıdır.
		</p>
	  </footer>
	  <style>
	    @import url("https://fonts.googleapis.com/css2?family=Poppins&display=swap");
		@import url("https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.15.1/css/all.min.css");
		
		* {
		  margin: 0;
		  padding: 0;
		  box-sizing: border-box;
		}
		
		*:focus,
		*:active {
		  outline: none !important;
		  -webkit-tap-highlight-color: transparent;
		}
		
		footer {
		  font-family: "Poppins", sans-serif;
		  position: relative;
		  bottom: 0px;
		  width: 100%;
		  display: flex;
		  align-items: center;
		  justify-content: space-between;
		  flex-direction: column;
		  padding: 20px 0px;
		  background: rgb(0, 0, 15);
		  border-top: aliceblue 5px solid;
		}
		
		p {
		  color: aliceblue;
		}
		
		.social {
		  display: flex;
		  flex-direction: column;
		  align-items: center;
		}
		
		.wrapper {
		  display: flex;
		  justify-content: center;
		  align-items: center;
		  padding-bottom: 40px;
		}
		
		.wrapper .icon {
		  position: relative;
		  background: aliceblue;
		  color: rgb(0, 0, 15);
		  border-radius: 50%;
		  margin: 10px;
		  width: 50px;
		  height: 50px;
		  font-size: 18px;
		  display: flex;
		  justify-content: center;
		  align-items: center;
		  flex-direction: column;
		  box-shadow: 0 10px 10px rgba(0, 0, 0, 0.1);
		  cursor: pointer;
		  transition: all 0.2s cubic-bezier(0.68, -0.55, 0.265, 1.55);
		}
		
		.wrapper .tooltip {
		  position: absolute;
		  top: 0;
		  font-size: 14px;
		  background: aliceblue;
		  color: aliceblue;
		  font-family: "Poppins", sans-serif;
		  padding: 5px 8px;
		  border-radius: 5px;
		  box-shadow: 0 10px 10px rgba(0, 0, 0, 0.1);
		  opacity: 0;
		  pointer-events: none;
		  transition: all 0.3s cubic-bezier(0.68, -0.55, 0.265, 1.55);
		}
		
		.wrapper .tooltip::before {
		  position: absolute;
		  content: "";
		  height: 8px;
		  width: 8px;
		  background: aliceblue;
		  top: -3px;
		  left: 50%;
		  transform: translate(-50%) rotate(45deg);
		  transition: all 0.3s cubic-bezier(0.68, -0.55, 0.265, 1.55);
		}
		
		.wrapper .icon:hover .tooltip {
		  top: 60px;
		  opacity: 1;
		  visibility: visible;
		  pointer-events: auto;
		}
		
		.wrapper .icon:hover span,
		.wrapper .icon:hover .tooltip {
		  text-shadow: 0px -1px 0px rgba(0, 0, 0, 0.1);
		}
		
		.wrapper .linkedin:hover,
		.wrapper .linkedin:hover .tooltip,
		.wrapper .linkedin:hover .tooltip::before {
		  background: #0077b5;
		  color: aliceblue;
		}
		
		.wrapper .facebook:hover,
		.wrapper .facebook:hover .tooltip,
		.wrapper .facebook:hover .tooltip::before {
		  background: #4267b2;
		  color: aliceblue;
		}
		
		.wrapper .twitter:hover,
		.wrapper .twitter:hover .tooltip,
		.wrapper .twitter:hover .tooltip::before {
		  background: #1da1f2;
		  color: aliceblue;
		}
		
		.wrapper .instagram:hover,
		.wrapper .instagram:hover .tooltip,
		.wrapper .instagram:hover .tooltip::before {
		  background: radial-gradient(
			circle at 30% 107%,
			#fdf497 0%,
			#fdf497 5%,
			#fd5949 45%,
			#d6249f 60%,
			#285aeb 90%
		  );
		  color: aliceblue;
		}
		
	
		</style>


</body>

</html>

main/templates/category-news.html
{% extends 'base.html' %}
{% block content %}
<main class="container mt-3 mb-5">
	<h3 class="border-bottom pb-1 my-4">{{category.title}}</h3>
    <!-- News Box -->
    {% for news in all_news %}
	<div class="card mb-4 shadow">
	  <div class="row no-gutters">
	    <div class="col-md-3">
            <img src="/media/{{news.image}}" class="card-img-top" alt="{{news.title}}">
	    </div>
	    <div class="col-md-8">
	      <div class="card-body">
	        <h5 class="card-title">{{news.title}}</h5>
	        <p style="color: black;" class="card-text">{{news.detail}}</p>
	        <p style="color: black;" class="card-text"><a href="/detail/{{news.id}}" class="btn btn-sm btn-primary">Hepsini Oku</a></p>
	      </div>
	    </div>
	  </div>
    </div>
    {% endfor %}
</main>
{% endblock %}

main/templates/category.html
{% extends 'base.html' %}
{% block content %}
<main class="container mt-3 mb-5">
	<h3 class="border-bottom pb-1 my-4">Gündem</h3>
	<div class="row">
		<!-- Category Box -->
		{% for cat in cats %}
		<div class="col-md-4">
			<div class="card mb-3 shadow">
            <img src="/media/{{cat.category_image}}" class="card-img-top" alt="{{cat.title}}">
			  <div class="card-body">
			    <h5 class="card-title">{{cat.title}}</h5>
			    <hr/>
			    <p style="color: black;" class="card-text"><a href="category/{{cat.id}}" class="btn btn-sm btn-primary">Hepsini Oku</a></p>
			  </div>
			</div>
		</div>
		{% endfor %}
	</div>
</main>
{% endblock %}

main/templates/detail.html
{% extends 'base.html' %}
{% block content %}
<main class="container mt-3 mb-5">
	<!-- featured news -->
	<div class="row my-3">
		<!-- Left -->
		<div class="col-md-8">
			<div class="card mb-3">
                <img src="/media/{{news.image}}" class="card-img-top" alt="{{news.title}}">
			  <div class="card-body">
			    <h5 class="card-title">{{news.title}}</h5>
			    <hr/>
			    <p style="color: black;" class="card-text">{{news.detail}}</p>
			  </div>
			  <div class="card-footer">
			 <a href="/category/{{news.category.id}}">{{news.category.title}}</a>
			  </div>
			</div>

			<!-- Comments -->
			<div class="card my-4">
				<h6 class="card-header">Yorum Bırak</h6>
				<div class="card-body">
					{% for message in messages %}
					<p class="text-success">{{message}}</p>
					{% endfor %}
					<form method="post" action="/detail/{{news.id}}">
						{% csrf_token %}
						<div class="form-group row">
							<label class="col-md-2">İsim<span class="text-danger">*</span></label>
							<div class="col-md-10">
								<input type="text" name="name" required class="form-control" />
							</div>
						</div>
						<div class="form-group row">
							<label class="col-md-2">Email<span class="text-danger">*</span></label>
							<div class="col-md-10">
								<input type="temailext" name="email" required class="form-control" />
							</div>
						</div>
						<div class="form-group row">
							<label class="col-md-2">Yorum<span class="text-danger">*</span></label>
							<div class="col-md-10">
								<textarea class="form-control" name="message" required></textarea>
							</div>
						</div>
						<input type="submit" class="btn btn-primary" />
					</form>
				</div>
			</div>
			<!-- Previous Comments -->
			<div class="card my-4">
				<h6 class="card-header">Comments</h6>
				<div class="card-body">
					{% for comment in comments %}
					<blockquote class="blockquote text-right">
					  <p class="mb-0">{{comment.comment}}</p>
					  <footer class="blockquote-footer">{{comment.name}} <cite title="Source Title">{{comment.email}}</cite></footer>
					</blockquote>
					<hr/>
					{% endfor %}
				</div>
			</div>
		</div>
		<!-- Related News -->
		<div class="col-md-4">
			<h3 class="mb-3 border-bottom pb-1">From this Category</h3>
			<!-- Category Box -->
			{% for news in related_news %}
			<div class="card mb-3 shadow">
                <img src="/media/{{news.image}}" class="card-img-top" alt="{{news.title}}">
			  <div class="card-body">
			    <h5 class="card-title">{{news.title}}</h5>
			    <hr/>
			    <p style="color: black;" class="card-text"><a href="/detail/{{news.id}}" class="btn btn-sm btn-primary">Hepsini Oku</a></p>
			  </div>
			</div>
			{% endfor %}
		</div>
	</div>
</main>
{% endblock %}

main/templates/home.html
{% extends 'base.html' %}
{% block content %}

<div class="content-area">
	<div class="banner">
		<h1>Only Artificial Intelligence
		</h1>
		<h2><span class="border"> WEB</span> <span class="noborder"> EWER</span>  </h2>
	</div>
</div>
<style>
	.border {
			background-color: #1da1f2;
			border-radius: 10%;
			padding: 0 5px;
		}

		.noborder {
			color: white;
		
		}
	@media only screen and (max-width: 970px) {
  .banner {
    text-align: center;
  }
</style>
<main class="container mt-3 mb-5">
	<!-- featured news -->
	<div class="row my-3">
		<div class="col-md-7">
			<div class="card mb-3">
			  <img src="media/{{first_news.image}}" class="card-img-top" alt="{{first_news.title}}">
			  <div class="card-body">
			    <h5 class="card-title">{{first_news.title}}</h5>
			    <hr/>
			    <p style="color: black;" class="card-text"><a href="/detail/{{first_news.id}}" class="btn btn-sm btn-primary">Hepsine Oku</a></p>
			  </div>
			</div>
		</div>
		<div class="col-md-5" style="max-height: 450px; overflow: auto;">
			{% for news in three_news %}
			<!-- News Box -->
			<div class="card">
			  <div class="row no-gutters">
			    <div class="col-md-4">
					<img src="media/{{news.image}}" class="card-img-top" alt="{{news.title}}">
			    </div>
			    <div class="col-md-8">
			      <div class="card-body">
			        <h5 class="card-title">{{news.title}}</h5>
			        <p style="color: black;" class="card-text"><a href="/detail/{{news.id}}" class="btn btn-sm btn-primary">Hepsini Oku</a></p>
			      </div>
			    </div>
			  </div>
			</div>
			<hr/>
			{% endfor %}
		</div>
	</div>
	{% for category in three_categories %}
	<h3 class="border-bottom pb-1">{{category.title}} <a href="/category/{{category.id}}" class="float-right btn btn-sm btn-dark">Daha Fazlası</a></h3>
	<div class="row my-4">
		{% for news in category.news_set.all %}
			{% if forloop.counter < 5 %}
			<!-- News box -->
			<div class="col-md-3">
				<div class="card mb-3 shadow">
				<img src="/media/{{news.image}}" class="card-img-top" alt="{{news.title}}">
				<div class="card-body">
					<h5 class="card-title">{{news.title}}</h5>
					<hr/>
					<p style="color: black;" class="card-text"><a href="/detail/{{news.id}}" class="btn btn-sm btn-primary">Hepsini Oku</a></p>
				</div>
				</div>
			</div>
			{% endif %}
		{% endfor %}
	</div>
	{% endfor %}
</main>
{% endblock %}